const BUILD="20261004-impact-1";
const app=document.getElementById("app");
const S={id:localStorage.sd_id||"",code:localStorage.sd_code||"",week:Number(localStorage.sd_week||1),viewName:"dashboard",league:null,me:null,view:null,matchups:null,submissions:null,live:null,lineup:{QB:[],RB:[],WR:[],FLEX:[]},poolReadySeen:localStorage.sd_pool_ready||""};
const draftKey=()=>`sd_draft_${S.id}_${S.code}_${S.week}`;
const saveDraft=()=>localStorage.setItem(draftKey(),JSON.stringify(S.lineup));
const clearDraft=()=>localStorage.removeItem(draftKey());
const loadDraft=()=>{try{const raw=localStorage.getItem(draftKey());return raw?JSON.parse(raw):null}catch{return null}};
let liveTimer=null;
const esc=x=>String(x??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
const empty=()=>({QB:[],FLEX:[],multipliers:{ace:null,impact:null}});
const slotIds=l=>[...(l?.QB||[]),...(l?.FLEX||[])];
const multiplierIds=l=>[l?.multipliers?.ace,l?.multipliers?.impact].filter(Boolean);
const save=()=>{localStorage.sd_id=S.id;localStorage.sd_code=S.code;localStorage.sd_week=S.week};
const countLineup=l=>slotIds(l).length;
const money=n=>"$"+Number(n||0).toLocaleString("en-US");
async function api(path,opt={}){const headers={"Content-Type":"application/json"};if(S.code)headers["x-team-code"]=S.code;const r=await fetch(path,{...opt,headers,cache:"no-store",body:opt.body?JSON.stringify(opt.body):undefined});let d={};try{d=await r.json()}catch{}if(!r.ok)throw Error(d.error||"Request failed");return d}
function requestBrowserAlerts(){if(!("Notification"in window)){alert("Browser notifications are not supported here.");return}Notification.requestPermission().then(p=>{if(p==="granted")alert("CAPPED alerts are enabled on this device.")})}
function derivedGroup(){const teamId=S.me?.team?.id;return (S.league?.groups||[]).find(g=>g.teamIds?.includes(teamId))||null}
function effectiveGroupId(){return S.me?.team?.groupId||S.me?.groupId||S.view?.matchup?.groupId||derivedGroup()?.id||null}
function effectiveGroupName(){return S.me?.team?.groupName||S.me?.groupName||S.view?.matchup?.groupName||derivedGroup()?.name||"—"}
function groupPool(){const gid=effectiveGroupId();const matches=S.matchups?.matchups||[];const shared=matches.find(m=>m.groupId===gid&&Array.isArray(m.pool)&&m.pool.length);if(shared?.pool?.length)return shared.pool;const mine=S.view?.matchup?.pool;if(Array.isArray(mine)&&mine.length)return mine;const leagueWeek=S.league?.weeks?.find(w=>w.week===S.week);const fallback=leagueWeek?.matchups?.find(m=>m.groupId===gid&&Array.isArray(m.pool)&&m.pool.length);return fallback?.pool||[]}
function groupPoolReady(){return !!S.view?.poolReadyAt||groupPool().length>0}
function groupPoolCount(){const gid=effectiveGroupId();return (S.matchups?.matchups||[]).filter(m=>m.groupId===gid&&!m.teamIds?.[1]&&m.pool?.length).length}
function notifyPoolReady(){if(!groupPool().length)return;const key=S.id+"-"+S.week+"-"+(S.view.poolReadyAt||"ready");if(S.poolReadySeen===key)return;S.poolReadySeen=key;localStorage.sd_pool_ready=key;if("Notification"in window&&Notification.permission==="granted")try{new Notification("CAPPED player pool is ready",{body:"Your group's unique player pool is ready. Build your lineup."})}catch{}}
function home(msg=""){app.innerHTML=`<section class="card"><div class="hero-brand"><div class="mini-logo"><span style="font-weight:1000;color:#c9953e">C</span></div><div><h1>Play Capped</h1><p class="muted">Salary-cap fantasy football played head-to-head.</p></div></div>${msg?'<p class="err">'+esc(msg)+'</p>':""}<h2>Create a league</h2><form id="create"><input name="name" placeholder="League name" required><div class="grid"><label>Season<input name="season" type="number" value="2026"></label><label>First NFL week<input name="startWeek" type="number" value="4"></label><label>Weeks<input name="numWeeks" type="number" value="8"></label><label>Salary cap<input name="budget" type="number" value="55000"></label></div><label>Team names — one per line<textarea name="teams" rows="5" placeholder="Brian\nMike\nJohn" required></textarea></label><select name="provider"><option value="sleeper">Real NFL data</option><option value="mock">Demo data</option></select><button>Create Capped League</button></form><hr><h2>Join a league</h2><form id="join"><input name="id" placeholder="League ID" required><input name="code" placeholder="Your team access code" required><button>Join League</button></form></section>`;document.getElementById("create").onsubmit=create;document.getElementById("join").onsubmit=join}
async function create(e){e.preventDefault();try{const f=new FormData(e.target);const d=await api("/api/leagues",{method:"POST",body:{name:f.get("name"),season:+f.get("season"),startWeek:+f.get("startWeek"),numWeeks:+f.get("numWeeks"),budget:+f.get("budget"),provider:f.get("provider"),teams:String(f.get("teams")).split("\n").map(x=>x.trim()).filter(Boolean)}});S.id=d.league.id;S.code=d.codes[0].code;S.week=1;save();showCodes(d.codes)}catch(x){home(x.message)}}
async function join(e){e.preventDefault();try{const f=new FormData(e.target);S.id=String(f.get("id")).trim().toLowerCase();S.code=String(f.get("code")).trim().toUpperCase();S.week=1;save();await load()}catch(x){localStorage.removeItem("sd_id");localStorage.removeItem("sd_code");S.id="";S.code="";home(x.message)}}
function showCodes(codes){app.innerHTML=`<section class="card"><h2>League created</h2><p>Give each friend their own code. The league ID is shared by everyone.</p>${codes.map(c=>`<p><b>${esc(c.name)}</b>: <span class="copy">${esc(c.code)}</span></p>`).join("")}<button id="continue">Enter League</button></section>`;document.getElementById("continue").onclick=load}
async function load(){try{S.league=await api("/api/leagues/"+S.id);S.me=await api("/api/leagues/"+S.id+"/me");S.view=await api("/api/leagues/"+S.id+"/weeks/"+S.week);S.matchups=await api("/api/leagues/"+S.id+"/weeks/"+S.week+"/matchups");const gp=groupPool();if(S.view.matchup&&!S.view.matchup.pool?.length&&gp.length)S.view.matchup.pool=gp;if(S.me.team.isCommish)S.submissions=await api("/api/leagues/"+S.id+"/weeks/"+S.week+"/submissions");const serverLineup=S.view.matchup?.myLineup;const serverCount=countLineup(serverLineup);S.lineup=serverCount>0||S.view.matchup?.submitted?serverLineup:loadDraft()||empty();if(S.lineup.multipliers?.champion&&!S.lineup.multipliers?.impact){S.lineup.multipliers.impact=S.lineup.multipliers.champion;delete S.lineup.multipliers.champion}notifyPoolReady();render();startLivePolling()}catch(x){home(x.message)}}
async function refreshLive(shouldRender=true){try{if(!S.id||!S.code||!S.view||["pending","final"].includes(S.view.week.status))return;const previous=S.live;S.live=await api("/api/leagues/"+S.id+"/weeks/"+S.week+"/live");if(shouldRender){render();requestAnimationFrame(()=>{const oldMap={};(previous?.matchups||[]).forEach(m=>(m.teams||[]).forEach(t=>oldMap[m.id+"-"+t.id]=Number(t.score)));document.querySelectorAll(".score-number").forEach(el=>{const n=Number(el.dataset.score),o=oldMap[el.dataset.teamKey];if(!Number.isFinite(n)||!Number.isFinite(o)||n===o)return;el.classList.add(n>o?"score-up":"score-down");setTimeout(()=>el.classList.remove("score-up","score-down"),900)})})}}catch{}}
function startLivePolling(){if(liveTimer)clearInterval(liveTimer);if(S.view&&!["pending","final"].includes(S.view.week.status)){refreshLive(false);liveTimer=setInterval(()=>refreshLive(S.viewName!=="team"),15000)}}
function nav(){return '<nav class="tabs">'+[["dashboard","Home"],["team","My Team"],["live","Live"],["matchups","Matchups"],["standings","Standings"],["players","Players"],["rules","Rules"],["commissioner","Commissioner"]].map(([v,label])=>'<button class="'+(S.viewName===v?"active":"")+'" data-nav="'+v+'">'+label+'</button>').join("")+'</nav>'}
function leagueHeader(){const l=S.league,w=S.view,poolReady=groupPoolReady();return '<section class="card"><div class="bar"><div><div class="eyebrow">CAPPED LEAGUE</div><h1>'+esc(l.name)+'</h1><span class="pill">Week '+S.week+'</span> <span class="pill">NFL '+w.week.nflWeek+'</span> <span class="pill">'+esc(w.week.status.toUpperCase())+'</span></div><button class="secondary" id="leave">Switch League</button></div><p>League ID: <b class="copy">'+esc(l.id)+'</b> · Salary Cap: <b>'+money(l.budget)+'</b> · Player Pool: <b class="pill">'+(poolReady?'READY':'NOT READY')+'</b></p><div class="bar"><button id="prev" class="secondary">Previous</button><button id="next" class="secondary">Next</button></div></section>'}
function shell(content){app.innerHTML=leagueHeader()+nav()+content;bindNav();bindWeekButtons()}
function statusIcon(state){return '<span class="status-icon '+state+'" aria-label="'+(state==='complete'?'Complete':state==='progress'?'In progress':'Not ready')+'"></span>'}
function statusCard(m){const poolReady=groupPoolReady(),selected=countLineup(S.lineup),submitted=!!S.view.matchup?.submitted,status=S.view.week.status;const poolState=poolReady?'complete':'not-ready',lineupState=submitted?'complete':selected>0?'progress':'not-ready',weekState=['locked','final'].includes(status)?'complete':status==='open'?'progress':'not-ready';return '<div class="grid"><div class="group-card status-section '+poolState+'"><div class="eyebrow">PLAYER POOL</div><div class="status-title">'+statusIcon(poolState)+'<h3>'+(poolReady?'READY':'NOT READY')+'</h3></div><p class="muted">'+(poolReady?'Your unique group pool is available.':S.view.week.status==='open'?'Waiting for the commissioner to generate your group pool.':'Waiting for the commissioner to open the week.')+'</p></div><div class="group-card status-section '+lineupState+'"><div class="eyebrow">LINEUP</div><div class="status-title">'+statusIcon(lineupState)+'<h3>'+(submitted?'SUBMITTED':selected>0?selected+'/8 SELECTED':'NOT SUBMITTED')+'</h3></div><p class="muted">'+(submitted?'Complete lineup — you can update before lock.':selected>0?'Keep going — select '+(8-selected)+' more players.':'Build and submit your 8-player lineup.')+'</p></div><div class="group-card status-section '+weekState+'"><div class="eyebrow">WEEK STATUS</div><div class="status-title">'+statusIcon(weekState)+'<h3>'+esc(status.toUpperCase())+'</h3></div><p class="muted">'+(S.view.week.lockAt?'Locks '+new Date(S.view.week.lockAt).toLocaleString():'Lock time set when week opens.')+'</p></div></div>'}
function dashboardView(){const l=S.league,w=S.view,m=w.matchup,my=S.me?.team?.id,r=(l.standings||[]).find(x=>x.teamId===my),rows=l.weeks.find(x=>x.week===S.week)?.matchups||[],g=(l.groups||[]).find(x=>x.teamIds?.includes(my));return '<section class="card"><div class="hero-brand"><div><div class="eyebrow">WEEK '+S.week+'</div><h2>Build under the cap. Win your group.</h2><p class="muted">You are in '+esc(effectiveGroupName())+'. Your group shares a unique player pool that other groups do not receive.</p></div></div>'+statusCard(m)+'<div class="grid"><div class="group-card"><h3>Season Points</h3><strong>'+Number(r?.standingsPoints??r?.pts??0)+'</strong><p class="muted">Placement points</p></div><div class="group-card"><h3>Group</h3><strong>'+esc(g?.name||effectiveGroupName())+'</strong><p class="muted">'+(g?.teamIds?.length||0)+' teams competing this week</p></div><div class="group-card"><h3>Notifications</h3><strong>Automatic</strong><p class="muted">Pool-ready alerts are checked automatically.</p><small class="muted">Build 20261004-impact-1</small><button class="secondary" id="enableAlerts">Enable browser alerts</button></div></div></section>'+(m?lineup(m,l):'<section class="card"><h2>Group Competition</h2><p>Your group competition is loading.</p></section>')}function teamView(){const m=S.view.matchup,l=S.league;if(!m)return '<section class="card"><h2>My Team</h2><p>You are not assigned to a group this week.</p></section>';return lineup(m,l)}
function liveForTeam(id,matchupId=S.view.matchup?.id){const mm=S.live?.matchups?.find(x=>x.id===matchupId);return mm?.teams?.find(x=>x.id===id)||null}
function matchupsView(){
 const comps=S.matchups?.matchups||[],liveRows=S.live?.matchups||[],mine=S.me?.team?.id;
 const teamLive=(m,id)=>liveRows.find(x=>x.id===m.id)?.teams?.find(x=>x.id===id);
 const poolFor=m=>m.pool||S.matchups?.matchups?.find(x=>x.id===m.id)?.pool||[];
 const gameFor=player=>player?.team?(S.live?.schedule||[]).find(g=>g.home===player.team||g.away===player.team):null;
 const gameState=g=>{if(!g)return{label:"STATUS UNKNOWN",key:"unknown"};const s=String(g.status||"").toLowerCase().replace(/[_-]/g," ");if(/postponed|cancelled|canceled/.test(s))return{label:"NOT PLAYING",key:"final"};if(/final|complete|ended/.test(s))return{label:"FINAL",key:"final"};if(/halftime|half time|half/.test(s))return{label:"HALFTIME",key:"halftime"};const k=Date.parse(g.date);if(Number.isFinite(k)&&Date.now()<k)return{label:"UPCOMING",key:"upcoming"};return{label:"LIVE",key:"live"}};
 const playerBreakdown=(m,t)=>{if(!t?.lineup)return"";const pool=poolFor(m),ids=[...(t.lineup.QB||[]),...(t.lineup.FLEX||[])];return ids.map(id=>{const p=pool.find(x=>x.id===id);if(!p)return"";const g=gameFor(p),gs=gameState(g),raw=Number(t.playerPoints?.[id]||0),ace=t.lineup.multipliers?.ace===id,impact=t.lineup.multipliers?.impact===id,pts=raw*(ace?2:impact?1.5:1),opp=g?(p.team===g.home?g.away:g.home):"";return '<div class="live-player-row"><span><b>'+esc(p.name)+'</b><small>'+esc(p.pos)+' · '+esc(p.team||'')+(opp?' · '+(p.team===g.home?'vs ':'@ ')+esc(opp):'')+(ace?' ⭐ ACE 2×':impact?' 🔥 IMPACT 1.5×':'')+'</small></span><strong>'+pts.toFixed(1)+' <em class="game-status '+gs.key+'">'+gs.label+'</em></strong></div>'}).join("")};
 let out='<section class="card live-scoreboard"><div class="bar"><div><h2>Group Competition</h2><p class="muted">Every team competes within its group.</p></div><span class="pill live-pill">● LIVE</span></div>';
 let lastGroup=null;
 comps.forEach(m=>{const g=(S.league.groups||[]).find(x=>x.id===m.groupId),lr=liveRows.find(x=>x.id===m.id),teams=(m.teamIds||[]).map(id=>teamLive(m,id)||{id,name:S.league.teams.find(t=>t.id===id)?.name||"Team"});if(g?.id!==lastGroup){out+='<div class="eyebrow group-label">'+esc(g?.name||"GROUP")+'</div>';lastGroup=g?.id}const ranked=teams.map(t=>({t,score:t.score})).sort((a,b)=>(b.score??-1)-(a.score??-1));out+='<div class="live-match"><div class="match-head"><span class="muted">'+esc(g?.name||"GROUP")+'</span><span class="muted">'+(m.result?'FINAL':'LIVE')+'</span></div><div class="group-scoreboard">'+ranked.map((r,i)=>'<div class="group-score-row '+(r.t.id===mine?"my-match":"")+'"><span><b>'+ (i+1)+'. '+esc(r.t.name)+'</b>'+(r.t.id===mine?' <small>YOU</small>':'')+'</span><strong>'+ (r.score!=null?Number(r.score).toFixed(1):"—")+'</strong><span class="placement-points">'+(m.result?.placementPoints?.[r.t.id]||"—")+' pts</span></div>').join("")+'</div>';
 const mineTeam=teams.find(x=>x.id===mine);if(mineTeam?.lineup)out+='<details class="live-details" open><summary>My player scoring</summary>'+playerBreakdown(m,mineTeam)+'</details>';out+='</div>'});
 out+='<p class="muted live-updated">Scores refresh every 15 seconds. Rankings and placement points update automatically.</p></section>';return out;
}
function liveView(){return matchupsView().replace("<h2>Live Matchups</h2>","<h2>Live Scoreboard</h2>")}
function standingsView(){
 const teams=S.league.teams||[], comps=S.matchups?.matchups||[], live=S.live?.matchups||[];
 let out='<section class="card"><div class="bar"><div><h2>Standings</h2><p class="muted">Weekly placement points: 1st gets the highest points in the group, then descending to 1 point.</p></div><span class="pill">WEEK '+S.week+'</span></div>';
 const groupTable=g=>{const rows=(g.teamIds||[]).map(id=>{const tm=teams.find(t=>t.id===id),r=(S.league.standings||[]).find(x=>x.teamId===id),lv=live.flatMap(m=>m.teams||[]).find(t=>t.id===id);return{name:tm?.name||"Team",score:lv?.score??null,season:r?.standingsPoints??r?.pts??0,pf:r?.pf??0,id}});return '<div class="group-card"><div class="bar"><b>'+esc(g.name)+'</b><span class="pill">'+rows.length+' teams</span></div><table class="standings"><tr><th>#</th><th>Team</th><th>Week '+S.week+'</th><th>Pts</th><th>Season</th></tr>'+rows.sort((a,b)=>(b.score??-1)-(a.score??-1)).map((r,i)=>'<tr><td>'+ (i+1)+'</td><td>'+esc(r.name)+'</td><td>'+ (r.score==null?'—':Number(r.score).toFixed(1))+'</td><td>'+Math.max(rows.length-i,1)+'</td><td>'+r.season+'</td></tr>').join("")+'</table></div>'};
 for(const g of S.league.groups||[])out+=groupTable(g);
 out+='<div class="group-card"><h3>League Standings</h3><p class="muted">Season standings are based on accumulated weekly placement points. Total fantasy points break ties.</p><table class="standings"><tr><th>#</th><th>Team</th><th>Pts</th><th>Total PF</th></tr>'+[...(S.league.standings||[])].map((r,i)=>'<tr><td>'+ (i+1)+'</td><td>'+esc(r.name)+'</td><td>'+ (r.standingsPoints??r.pts??0)+'</td><td>'+Number(r.pf||0).toFixed(1)+'</td></tr>').join("")+'</table></div></section>';return out;
}
function injuryLabel(p){const s=String(p.injuryStatus||"healthy").toLowerCase();if(s==="healthy")return '<span class="good">Healthy</span>';if(s==="questionable")return '<span class="err">Q — Questionable</span>';return '<span class="err">'+esc(s.replaceAll("_"," "))+'</span>'}
function playersView(){const pool=groupPool();if(!pool.length)return '<section class="card"><h2>Your Group Player Pool</h2><p class="muted">Your unique group player pool has not loaded yet.</p><p class="err">If the commissioner has generated the pool, refresh the league and try again.</p></section>';return '<section class="card"><h2>Your Group Player Pool</h2><p class="muted">Every team in your group receives this same unique pool. Out/IR/inactive players are excluded; questionable players are clearly marked.</p><div class="grid">'+pool.map(p=>'<div class="player"><span><b>'+esc(p.name)+'</b><small>'+esc(p.pos)+' · '+esc(p.team)+' · '+(p.opponent?esc(p.homeAway||'vs')+' '+esc(p.opponent)+' · ':'')+p.proj+' proj · '+injuryLabel(p)+'</small></span><b>'+money(p.salary)+'</b></div>').join("")+'</div></section>'}
function rulesView(){return '<section class="card"><h2>How Capped Works</h2><ol><li>Build an 8-player lineup — 1 QB and 7 FLEX — while staying under the salary cap.</li><li>Your league is divided into groups.</li><li>Each group receives its own unique player pool and salaries.</li><li>Teams compete only against opponents in their own group.</li><li>Healthy and questionable players can appear; out, IR and inactive players are excluded.</li><li>Submit before the weekly lock. Live scores update automatically while games are active.</li></ol><h3>Roster</h3><p>1 QB · 7 FLEX (RB/WR/TE)</p><h3>CAP’D</h3><p>If your lineup exceeds the salary cap, CAPPED flags it immediately and prevents submission.</p></section>'}
function commissionerView(){const poolReady=groupPoolReady();if(!isCommish())return '<section class="card"><h2>Commissioner</h2><p>This tab is available to the league commissioner.</p></section>';const groups=S.league.groups||[],teams=S.league.teams||[],sub=S.submissions;
const matchupRows=S.matchups?.matchups||[];
const submittedFromMatchups=new Set(matchupRows.flatMap(m=>Object.keys(m.teams||{}).filter(()=>false)));
const submittedIds=new Set(matchupRows.flatMap(m=>(m.teams||[]).filter(x=>x.submitted).map(x=>x.id)));
const submitted=submittedIds.size;
const total=teams.length;let out='<section class="card"><div class="bar"><div><h2>Commissioner Dashboard</h2><p class="muted">Open, lock, score and monitor every team.</p></div><span class="pill">'+esc(S.view.week.status.toUpperCase())+'</span></div><div class="grid"><div class="group-card"><h3>'+submitted+' / '+total+'</h3><p class="muted">Lineups submitted</p></div><div class="group-card"><h3>'+(submitted===total?'READY TO LOCK':'WAITING')+'</h3><p class="muted">'+(submitted===total?'Everyone is in.':'Teams still need to submit.')+'</p></div><div class="group-card"><h3>'+(poolReady?'READY':'NOT READY')+'</h3><p class="muted">Player pool status</p></div></div><div class="bar" style="margin-top:14px"><span><b>Week controls</b><br><span class="muted">Open generates the unique pools for each group.</span></span><span><button id="openWeek" class="secondary">Open Week</button> <button id="generatePool" class="secondary">Generate Player Pool</button> <button id="lockWeek" class="secondary">Lock Week</button> <button id="scoreWeek" class="secondary">Score Week</button></span></div></section>';if(sub?.teams){for(const g of groups){out+='<section class="card"><div class="bar"><h3>'+esc(g.name)+'</h3><span class="pill">'+g.teamIds.length+' teams</span></div>'+sub.teams.filter(t=>t.groupId===g.id).map(t=>'<div class="player"><span><b>'+esc(t.name)+'</b><small>'+(t.submitted?'Lineup submitted':'Waiting for lineup')+'</small></span><b class="'+(t.submitted?'good':'err')+'">'+(t.submitted?'✓ READY':'NOT READY')+'</b></div>').join("")+'</section>'}}return out}
function salary(lineup){
  const pool=S.view?.matchup?.pool||groupPool();
  const byId=new Map((Array.isArray(pool)?pool:[]).map(p=>[p.id,p]));
  return slotIds(lineup).reduce((sum,id)=>sum+(Number(byId.get(id)?.salary)||0),0);
}
function multiplierRole(id){if(S.lineup.multipliers?.ace===id)return "ace";if(S.lineup.multipliers?.impact===id)return "impact";return null}
function multiplierBadge(id){const r=multiplierRole(id);return r=== "ace"?" ⭐ ACE · 2×":r==="impact"?" 🏆 IMPACT · 1.5×":""}
function multiplierControls(id){const role=multiplierRole(id);return `<div class="multiplier-controls"><button type="button" class="multiplier-btn ${role==="ace"?"active":""}" data-multiplier="ace" data-id="${esc(id)}">⭐ ACE <small>2×</small></button><button type="button" class="multiplier-btn ${role==="impact"?"active":""}" data-multiplier="impact" data-id="${esc(id)}">🏆 IMPACT <small>1.5×</small></button></div>`}
function budgetTracker(l){
  const spent=salary(S.lineup), budget=Number(l.budget||0), remaining=budget-spent;
  const state=remaining<0?"over":remaining===0?"zero":"good";
  return '<div class="budget-tracker '+state+'"><div><span class="budget-label">SPENT</span><strong>'+money(spent)+'</strong></div><div><span class="budget-label">REMAINING</span><strong>'+money(Math.max(remaining,0))+'</strong></div><div><span class="budget-label">SALARY CAP</span><strong>'+money(budget)+'</strong></div></div>';
}
function isCommish(){return !!S.me?.team?.isCommish}
function wDisabled(m){return !m||!m.pool?.length||["locked","final"].includes(S.view.week.status)}
function slot(key,title,max,pool){return '<div class="slot"><h3>'+title+' <span class="muted">('+S.lineup[key].length+'/'+max+')</span></h3>'+(key==="FLEX"?'<p class="muted">RB · WR · TE</p>':"")+(S.lineup[key].map(id=>{const p=pool.find(x=>x.id===id);return p?'<div class="player selected"><span><b>'+esc(p.name)+'</b><small>'+esc(p.pos)+' · '+esc(p.team||'')+(p.opponent?' · '+esc(p.homeAway||'vs')+' '+esc(p.opponent):'')+' · '+money(p.salary)+multiplierBadge(id)+'</small>'+multiplierControls(id)+'</span><button class="remove" data-id="'+esc(id)+'" data-slot="'+key+'">Remove</button></div>':""}).join("")||'<p class="muted">Empty</p>')+'</div>'}
function player(p){const current=["QB","FLEX"].map(k=>[k,S.lineup[k]||[]]).find(([k,ids])=>ids.includes(p.id));return '<div class="player '+(current?"selected":"")+'"><span><b>'+esc(p.name)+'</b><small>'+esc(p.pos)+' · '+esc(p.team)+' · '+(p.opponent?' · <b class="matchup">'+esc(p.homeAway||'vs')+' '+esc(p.opponent)+'</b>':'')+' · '+p.proj+' proj · '+money(p.salary)+' · '+injuryLabel(p)+'</small></span>'+(current?'<button class="remove" data-id="'+esc(p.id)+'" data-slot="'+current[0]+'">Remove</button>':'<select class="assign" data-id="'+esc(p.id)+'"><option value="">Add to…</option>'+(p.pos==="QB"?'<option value="QB">QB</option>':"")+(["RB","WR","TE"].includes(p.pos)?'<option value="FLEX">FLEX</option>':"")+'</select>')+'</div>'}
function lineup(m,l){const pool=m.pool||[],groups={QB:pool.filter(p=>p.pos==="QB"),RB:pool.filter(p=>p.pos==="RB"),WR:pool.filter(p=>p.pos==="WR"),TE:pool.filter(p=>p.pos==="TE")},slots=[["QB","QB",1],["FLEX","FLEX",7]],sal=salary(S.lineup),complete=countLineup(S.lineup)===8,submitted=!!S.view.matchup?.submitted,status=S.view.week.status,live=liveForTeam(S.me?.team?.id),oppLive=liveForTeam(m.opponent?.id);let out='<section class="card"><div class="bar"><div><h2>My Team</h2><p class="muted">Your group: '+esc(effectiveGroupName())+' · Pool is shared only within your group.</p></div>'+budgetTracker(l)+'</div>';if(sal>l.budget)out+='<div class="cap-warning"><div class="capd">CAP’D</div><div><b>You’re over the salary cap.</b><span>Drop '+money(sal-l.budget)+' to submit your lineup.</span></div></div>';else out+='<p class="good">'+(complete?"8 / 8 players selected":"Select "+(8-countLineup(S.lineup))+" more players")+'</p>';out+=statusCard(m);out+='<div class="group-card"><div class="bar"><div><b>Your lineup status:</b> '+(submitted?'SUBMITTED':'NOT SUBMITTED')+'</div><span class="pill">'+esc(status.toUpperCase())+'</span></div>'+(live?.score!=null?'<p class="muted">Live score: <b>'+live.score+'</b> · '+(oppLive?.score!=null?'Opponent: <b>'+oppLive.score+'</b>':'')+'</p>':"")+'</div><div class="slots">'+slots.map(([key,title,max])=>slot(key,title,max,pool)).join("")+'</div>'+budgetTracker(l)+'<div class="card" style="margin-top:14px;background:#f8fafc"><h3>Available Players</h3><p class="muted">Add 1 QB and 7 FLEX players (RB, WR or TE). Questionable players are allowed and marked Q.</p>'+groups.QB.map(player).join("")+groups.RB.map(player).join("")+groups.WR.map(player).join("")+groups.TE.map(player).join("")+'</div><div class="bar"><button id="saveLineup" type="button" '+(!complete||sal>l.budget||wDisabled(m)?"disabled":"")+'>'+(submitted?'Update Lineup':'Submit Lineup')+'</button>'+(isCommish()?'<span><button id="openWeek" class="secondary">Open Week</button> <button id="lockWeek" class="secondary">Lock Week</button> <button id="scoreWeek" class="secondary">Score Week</button></span>':"")+'</div>';if(m.result)out+=resultBox(m);out+='<p class="muted">Opponent: '+esc(m.opponent?.name||"Bye")+' · Your opponent receives the exact same player pool and salaries.</p></section>';return out}
function resultBox(m){const oid=m.opponent?.id,mine=S.me?.team?.id;return '<div class="card"><h3>Final score</h3><p>Your score: <b>'+(m.result.points[mine]??"—")+'</b></p><p>Opponent: <b>'+(oid?m.result.points[oid]:"—")+'</b></p></div>'}
function bindNav(){document.querySelectorAll("[data-nav]").forEach(b=>b.onclick=()=>{S.viewName=b.dataset.nav;render()})}
function bindWeekButtons(){document.getElementById("leave")?.addEventListener("click",()=>{localStorage.removeItem("sd_id");localStorage.removeItem("sd_code");location.reload()});document.getElementById("prev")?.addEventListener("click",()=>{if(S.week>1){S.week--;save();load()}});document.getElementById("next")?.addEventListener("click",()=>{if(S.week<S.league.numWeeks){S.week++;save();load()}});document.getElementById("enableAlerts")?.addEventListener("click",requestBrowserAlerts)}
function render(){if(!S.league||!S.view)return;let content=S.viewName==="team"?teamView():S.viewName==="live"?liveView():S.viewName==="matchups"?matchupsView():S.viewName==="standings"?standingsView():S.viewName==="players"?playersView():S.viewName==="rules"?rulesView():S.viewName==="commissioner"?commissionerView():dashboardView();shell(content)}
document.addEventListener("change",e=>{if(!e.target.classList.contains("assign"))return;const id=e.target.dataset.id,slot=e.target.value,max={QB:1,FLEX:7}[slot];if(!slot)return;if(S.lineup[slot].length>=max){alert(slot+" is full");e.target.value="";return}if(Object.values(S.lineup).flat().includes(id)){e.target.value="";return}S.lineup[slot].push(id);saveDraft();render()});
document.addEventListener("click",async e=>{if(e.target.closest?.("[data-multiplier]")){const btn=e.target.closest("[data-multiplier]"),id=btn.dataset.id,role=btn.dataset.multiplier;S.lineup.multipliers ||= {ace:null,impact:null};if(S.lineup.multipliers[role]===id){S.lineup.multipliers[role]=null}else{const other=role==="ace"?"impact":"ace";S.lineup.multipliers[other]=S.lineup.multipliers[other]===id?null:S.lineup.multipliers[other];S.lineup.multipliers[role]=id}saveDraft();render();return}if(e.target.classList.contains("remove")){const id=e.target.dataset.id,slot=e.target.dataset.slot;S.lineup[slot]=S.lineup[slot].filter(x=>x!==id);saveDraft();render();return}try{if(e.target.id==="saveLineup"){const btn=e.target;btn.disabled=true;btn.textContent="Submitting…";await api("/api/leagues/"+S.id+"/weeks/"+S.week+"/lineup",{method:"PUT",body:{lineup:S.lineup}});clearDraft();await load()}else if(["openWeek","dashOpen"].includes(e.target.id)){await api("/api/leagues/"+S.id+"/weeks/"+S.week+"/open",{method:"POST"});await load()}else if(e.target.id==="generatePool"){const btn=e.target;btn.disabled=true;btn.textContent="Generating…";try{const d=await api("/api/leagues/"+S.id+"/weeks/"+S.week+"/generate-pool",{method:"POST"});if(!d.poolReady)throw Error("The server did not confirm the player pool is ready.");await load();alert("Player pool generated successfully. Your group player pool is now READY.");}catch(x){btn.disabled=false;btn.textContent="Generate Player Pool";alert("Player pool generation failed: "+x.message)}}else if(["lockWeek","dashLock"].includes(e.target.id)){await api("/api/leagues/"+S.id+"/weeks/"+S.week+"/lock",{method:"POST"});await load()}else if(["scoreWeek","dashScore"].includes(e.target.id)){await api("/api/leagues/"+S.id+"/weeks/"+S.week+"/score",{method:"POST"});await load()}}catch(x){alert(x.message)}});
if(S.id&&S.code)load();else home();