const app=document.getElementById("app");
const S={id:localStorage.sd_id||"",code:localStorage.sd_code||"",week:Number(localStorage.sd_week||1),viewName:"dashboard",league:null,me:null,view:null,matchups:null,submissions:null,live:null,lineup:{QB:[],RB:[],WR:[],FLEX:[]},poolReadySeen:localStorage.sd_pool_ready||""};
let liveTimer=null;
const esc=x=>String(x??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
const empty=()=>({QB:[],RB:[],WR:[],FLEX:[]});
const save=()=>{localStorage.sd_id=S.id;localStorage.sd_code=S.code;localStorage.sd_week=S.week};
const countLineup=l=>Object.values(l||{}).flat().length;
const money=n=>"$"+Number(n||0).toLocaleString("en-US");
async function api(path,opt={}){const headers={"Content-Type":"application/json"};if(S.code)headers["x-team-code"]=S.code;const r=await fetch(path,{...opt,headers,body:opt.body?JSON.stringify(opt.body):undefined});let d={};try{d=await r.json()}catch{}if(!r.ok)throw Error(d.error||"Request failed");return d}
function requestBrowserAlerts(){if(!("Notification"in window)){alert("Browser notifications are not supported here.");return}Notification.requestPermission().then(p=>{if(p==="granted")alert("CAPPED alerts are enabled on this device.")})}
function notifyPoolReady(){if(!S.view?.matchup?.pool?.length)return;const key=S.id+"-"+S.week+"-"+(S.view.poolReadyAt||"ready");if(S.poolReadySeen===key)return;S.poolReadySeen=key;localStorage.sd_pool_ready=key;if("Notification"in window&&Notification.permission==="granted")try{new Notification("CAPPED player pool is ready",{body:"Your group's unique player pool is ready. Build your lineup."})}catch{}}
function home(msg=""){app.innerHTML=`<section class="card"><div class="hero-brand"><div class="mini-logo"><span style="font-weight:1000;color:#c9953e">C</span></div><div><h1>Play Capped</h1><p class="muted">Salary-cap fantasy football played head-to-head.</p></div></div>${msg?'<p class="err">'+esc(msg)+'</p>':""}<h2>Create a league</h2><form id="create"><input name="name" placeholder="League name" required><div class="grid"><label>Season<input name="season" type="number" value="2026"></label><label>First NFL week<input name="startWeek" type="number" value="4"></label><label>Weeks<input name="numWeeks" type="number" value="8"></label><label>Salary cap<input name="budget" type="number" value="50000"></label></div><label>Team names — one per line<textarea name="teams" rows="5" placeholder="Brian\nMike\nJohn" required></textarea></label><select name="provider"><option value="sleeper">Real NFL data</option><option value="mock">Demo data</option></select><button>Create Capped League</button></form><hr><h2>Join a league</h2><form id="join"><input name="id" placeholder="League ID" required><input name="code" placeholder="Your team access code" required><button>Join League</button></form></section>`;document.getElementById("create").onsubmit=create;document.getElementById("join").onsubmit=join}
async function create(e){e.preventDefault();try{const f=new FormData(e.target);const d=await api("/api/leagues",{method:"POST",body:{name:f.get("name"),season:+f.get("season"),startWeek:+f.get("startWeek"),numWeeks:+f.get("numWeeks"),budget:+f.get("budget"),provider:f.get("provider"),teams:String(f.get("teams")).split("\n").map(x=>x.trim()).filter(Boolean)}});S.id=d.league.id;S.code=d.codes[0].code;S.week=1;save();showCodes(d.codes)}catch(x){home(x.message)}}
async function join(e){e.preventDefault();try{const f=new FormData(e.target);S.id=String(f.get("id")).trim().toLowerCase();S.code=String(f.get("code")).trim().toUpperCase();S.week=1;save();await load()}catch(x){localStorage.removeItem("sd_id");localStorage.removeItem("sd_code");S.id="";S.code="";home(x.message)}}
function showCodes(codes){app.innerHTML=`<section class="card"><h2>League created</h2><p>Give each friend their own code. The league ID is shared by everyone.</p>${codes.map(c=>`<p><b>${esc(c.name)}</b>: <span class="copy">${esc(c.code)}</span></p>`).join("")}<button id="continue">Enter League</button></section>`;document.getElementById("continue").onclick=load}
async function load(){try{S.league=await api("/api/leagues/"+S.id);S.me=await api("/api/leagues/"+S.id+"/me");S.view=await api("/api/leagues/"+S.id+"/weeks/"+S.week);S.matchups=await api("/api/leagues/"+S.id+"/weeks/"+S.week+"/matchups");if(S.me.team.isCommish)S.submissions=await api("/api/leagues/"+S.id+"/weeks/"+S.week+"/submissions");S.lineup=S.view.matchup?.myLineup||empty();notifyPoolReady();render();startLivePolling()}catch(x){home(x.message)}}
async function refreshLive(shouldRender=true){try{if(!S.id||!S.code||!S.view||["pending","final"].includes(S.view.week.status))return;S.live=await api("/api/leagues/"+S.id+"/weeks/"+S.week+"/live");if(shouldRender)render()}catch{}}
function startLivePolling(){if(liveTimer)clearInterval(liveTimer);if(S.view&&!["pending","final"].includes(S.view.week.status)){refreshLive(false);liveTimer=setInterval(()=>refreshLive(S.viewName!=="team"),30000)}}
function nav(){return '<nav class="tabs">'+[["dashboard","Home"],["team","My Team"],["matchups","Matchups"],["standings","Standings"],["players","Players"],["rules","Rules"],["commissioner","Commissioner"]].map(([v,label])=>'<button class="'+(S.viewName===v?"active":"")+'" data-nav="'+v+'">'+label+'</button>').join("")+'</nav>'}
function leagueHeader(){const l=S.league,w=S.view,poolReady=!!w.poolReadyAt||!!w.matchup?.pool?.length;return '<section class="card"><div class="bar"><div><div class="eyebrow">CAPPED LEAGUE</div><h1>'+esc(l.name)+'</h1><span class="pill">Week '+S.week+'</span> <span class="pill">NFL '+w.week.nflWeek+'</span> <span class="pill">'+esc(w.week.status.toUpperCase())+'</span></div><button class="secondary" id="leave">Switch League</button></div><p>League ID: <b class="copy">'+esc(l.id)+'</b> · Salary Cap: <b>'+money(l.budget)+'</b> · Player Pool: <b class="pill">'+(poolReady?'READY':'NOT READY')+'</b></p><div class="bar"><button id="prev" class="secondary">Previous</button><button id="next" class="secondary">Next</button></div></section>'}
function shell(content){app.innerHTML=leagueHeader()+nav()+content;bindNav();bindWeekButtons()}
function statusIcon(state){return '<span class="status-icon '+state+'" aria-label="'+(state==='complete'?'Complete':state==='progress'?'In progress':'Not ready')+'"></span>'}
function statusCard(m){const poolReady=!!S.view.poolReadyAt||!!m?.pool?.length,selected=countLineup(S.lineup),submitted=selected===8,status=S.view.week.status;const poolState=poolReady?'complete':'not-ready',lineupState=submitted?'complete':selected>0?'progress':'not-ready',weekState=['locked','final'].includes(status)?'complete':status==='open'?'progress':'not-ready';return '<div class="grid"><div class="group-card status-section '+poolState+'"><div class="eyebrow">PLAYER POOL</div><div class="status-title">'+statusIcon(poolState)+'<h3>'+(poolReady?'READY':'NOT READY')+'</h3></div><p class="muted">'+(poolReady?'Your unique group pool is available.':'Waiting for the commissioner to open the week.')+'</p></div><div class="group-card status-section '+lineupState+'"><div class="eyebrow">LINEUP</div><div class="status-title">'+statusIcon(lineupState)+'<h3>'+(submitted?'SUBMITTED':selected>0?selected+'/8 SELECTED':'NOT SUBMITTED')+'</h3></div><p class="muted">'+(submitted?'Complete lineup — you can update before lock.':selected>0?'Keep going — select '+(8-selected)+' more players.':'Build and submit your 8-player lineup.')+'</p></div><div class="group-card status-section '+weekState+'"><div class="eyebrow">WEEK STATUS</div><div class="status-title">'+statusIcon(weekState)+'<h3>'+esc(status.toUpperCase())+'</h3></div><p class="muted">'+(S.view.week.lockAt?'Locks '+new Date(S.view.week.lockAt).toLocaleString():'Lock time set when week opens.')+'</p></div></div>'}
function dashboardView(){const l=S.league,w=S.view,m=w.matchup,my=S.me?.team?.id,rec=(l.standings||[]).find(x=>x.id===my),rows=(l.weeks.find(x=>x.week===S.week)?.matchups||[]);return '<section class="card"><div class="hero-brand"><div><div class="eyebrow">WEEK '+S.week+'</div><h2>Build under the cap. Beat your opponent.</h2><p class="muted">You are in '+esc(S.me.groupName||"your group")+'. Your group shares a unique player pool that other groups do not receive.</p></div></div>'+statusCard(m)+'<div class="grid"><div class="group-card"><h3>My Record</h3><strong>'+(rec?(rec.w+"-"+rec.l+"-"+rec.t):"0-0-0")+'</strong><p class="muted">League standing</p></div><div class="group-card"><h3>Group</h3><strong>'+esc(S.me.groupName||"—")+'</strong><p class="muted">'+rows.filter(x=>x.groupId===S.me.groupId).length+' matchup(s) this week</p></div><div class="group-card"><h3>Notifications</h3><strong>Automatic</strong><p class="muted">Pool-ready alerts are checked automatically.</p><button class="secondary" id="enableAlerts">Enable browser alerts</button></div></div></section>'+(m?lineup(m,l):'<section class="card"><h2>Bye week</h2><p>You do not have a matchup this week.</p></section>')}
function teamView(){const m=S.view.matchup,l=S.league;if(!m)return '<section class="card"><h2>My Team</h2><p>You have a bye this week.</p></section>';return lineup(m,l)}
function liveForTeam(id,matchupId=S.view.matchup?.id){const mm=S.live?.matchups?.find(x=>x.id===matchupId);return mm?.teams?.find(x=>x.id===id)||null}
function matchupsView(){const rows=S.league.weeks.find(w=>w.week===S.week)?.matchups||[],mine=S.me?.team?.id;let out='<section class="card"><div class="bar"><div><h2>Matchups</h2><p class="muted">All matchups, organized by group. Live scores refresh automatically during games.</p></div><span class="pill">'+esc(S.view.week.status.toUpperCase())+'</span></div>';rows.forEach(m=>{const a=S.league.teams.find(t=>t.id===m.a),b=m.b&&S.league.teams.find(t=>t.id===m.b),mineHere=m.a===mine||m.b===mine,la=liveForTeam(m.a,m.id),lb=m.b?liveForTeam(m.b,m.id):null;out+='<div class="mini-match '+(mineHere?"selected":"")+'"><div class="eyebrow">'+esc((S.league.groups||[]).find(g=>g.id===m.groupId)?.name||"GROUP")+(mineHere?" · YOUR MATCHUP":"")+'</div><div class="duel"><div><strong>'+esc(a?.name||"BYE")+'</strong><span class="muted">'+(la?.score!=null?la.score:(m.result?.points?.[m.a]??"—"))+'</span><small class="muted">'+(la?.submitted?"Submitted":"")+'</small></div><span class="vs">VS</span><div><strong>'+esc(b?.name||"BYE")+'</strong><span class="muted">'+(b?(lb?.score!=null?lb.score:(m.result?.points?.[m.b]??"—")):"")+'</span><small class="muted">'+(lb?.submitted?"Submitted":"")+'</small></div></div></div>'});return out+'</section>'}
function standingsView(){
  const week=S.league.weeks.find(w=>w.week===S.week)||{};
  const teams=S.league.teams||[];
  const teamById=new Map(teams.map(t=>[t.id,t]));
  const groupById=new Map((S.league.groups||[]).map(g=>[g.id,g]));
  const weekly=new Map(teams.map(t=>[t.id,{teamId:t.id,name:t.name,w:0,l:0,t:0,pf:0,pa:0}]));
  for(const m of week.matchups||[]){
    if(m.b===null) continue;
    const a=weekly.get(m.a), b=weekly.get(m.b);
    const live=S.live?.matchups?.find(x=>x.id===m.id);
    const la=live?.teams?.find(x=>x.id===m.a), lb=live?.teams?.find(x=>x.id===m.b);
    const pa=m.result?.points?.[m.a]??la?.score, pb=m.result?.points?.[m.b]??lb?.score;
    if(pa==null||pb==null) continue;
    a.pf=Number(pa); a.pa=Number(pb); b.pf=Number(pb); b.pa=Number(pa);
    if(pa===pb){a.t++;b.t++;}else if(pa>pb){a.w++;b.l++;}else{b.w++;a.l++;}
  }
  const sortRows=rows=>rows.sort((a,b)=>b.w+b.t/2-(a.w+a.t/2)||b.pf-a.pf);
  const table=(rows,points)=>'<table class="standings"><tr><th>#</th><th>Team</th><th>W</th><th>L</th><th>T</th><th>PF</th><th>Pts</th></tr>'+rows.map((r,i)=>'<tr><td>'+(i+1)+'</td><td>'+esc(r.name)+'</td><td>'+r.w+'</td><td>'+r.l+'</td><td>'+r.t+'</td><td>'+Number(r.pf||0).toFixed(1)+'</td><td>'+((r.w*3)+r.t)+'</td></tr>').join("")+'</table>';
  let out='<section class="card"><div class="bar"><div><h2>Standings</h2><p class="muted">Weekly group competition and overall league standings.</p></div><span class="pill">WEEK '+S.week+'</span></div>';
  out+='<div class="group-card"><h3>Group Standings — Week '+S.week+'</h3><p class="muted">Your group’s weekly standings. Pts = 3 for a win, 1 for a tie.</p>';
  for(const g of S.league.groups||[]){
    const rows=sortRows(g.teamIds.map(id=>weekly.get(id)));
    out+='<div style="margin-top:14px"><div class="bar"><b>'+esc(g.name)+'</b><span class="pill">'+g.teamIds.length+' teams</span></div>'+table(rows,true)+'</div>';
  }
  out+='</div><div class="group-card"><h3>League Standings</h3><p class="muted">Season totals across all completed weeks.</p>';
  const overall=sortRows((S.league.standings||[]).map(r=>({...r})));
  out+=table(overall,true)+'</div></section>';
  return out;
}
function injuryLabel(p){const s=String(p.injuryStatus||"healthy").toLowerCase();if(s==="healthy")return '<span class="good">Healthy</span>';if(s==="questionable")return '<span class="err">Q — Questionable</span>';return '<span class="err">'+esc(s.replaceAll("_"," "))+'</span>'}
function playersView(){const pool=S.view.matchup?.pool||[];return '<section class="card"><h2>Your Group Player Pool</h2><p class="muted">Every team in your group receives this same unique pool. Out/IR/inactive players are excluded; questionable players are clearly marked.</p><div class="grid">'+pool.map(p=>'<div class="player"><span><b>'+esc(p.name)+'</b><small>'+esc(p.pos)+' · '+esc(p.team)+' · '+p.proj+' proj · '+injuryLabel(p)+'</small></span><b>'+money(p.salary)+'</b></div>').join("")+'</div></section>'}
function rulesView(){return '<section class="card"><h2>How Capped Works</h2><ol><li>Build an 8-player lineup while staying under the salary cap.</li><li>Your league is divided into groups.</li><li>Each group receives its own unique player pool and salaries.</li><li>Teams compete only against opponents in their own group.</li><li>Healthy and questionable players can appear; out, IR and inactive players are excluded.</li><li>Submit before the weekly lock. Live scores update automatically while games are active.</li></ol><h3>Roster</h3><p>1 QB · 2 RB · 3 WR · 2 FLEX (RB/WR/TE)</p><h3>CAP’D</h3><p>If your lineup exceeds the salary cap, CAPPED flags it immediately and prevents submission.</p></section>'}
function commissionerView(){if(!isCommish())return '<section class="card"><h2>Commissioner</h2><p>This tab is available to the league commissioner.</p></section>';const groups=S.league.groups||[],teams=S.league.teams||[],sub=S.submissions,submitted=sub?.submitted??0,total=sub?.total??teams.length;let out='<section class="card"><div class="bar"><div><h2>Commissioner Dashboard</h2><p class="muted">Open, lock, score and monitor every team.</p></div><span class="pill">'+esc(S.view.week.status.toUpperCase())+'</span></div><div class="grid"><div class="group-card"><h3>'+submitted+' / '+total+'</h3><p class="muted">Lineups submitted</p></div><div class="group-card"><h3>'+(submitted===total?'READY TO LOCK':'WAITING')+'</h3><p class="muted">'+(submitted===total?'Everyone is in.':'Teams still need to submit.')+'</p></div><div class="group-card"><h3>'+(S.view.poolReadyAt?'READY':'NOT READY')+'</h3><p class="muted">Player pool status</p></div></div><div class="bar" style="margin-top:14px"><span><b>Week controls</b><br><span class="muted">Open generates the unique pools for each group.</span></span><span><button id="openWeek" class="secondary">Open Week</button> <button id="generatePool" class="secondary">Generate Player Pool</button> <button id="lockWeek" class="secondary">Lock Week</button> <button id="scoreWeek" class="secondary">Score Week</button></span></div></section>';if(sub?.teams){for(const g of groups){out+='<section class="card"><div class="bar"><h3>'+esc(g.name)+'</h3><span class="pill">'+g.teamIds.length+' teams</span></div>'+sub.teams.filter(t=>t.groupId===g.id).map(t=>'<div class="player"><span><b>'+esc(t.name)+'</b><small>'+(t.submitted?'Lineup submitted':'Waiting for lineup')+'</small></span><b class="'+(t.submitted?'good':'err')+'">'+(t.submitted?'✓ READY':'NOT READY')+'</b></div>').join("")+'</section>'}}return out}
function salary(l){return Object.values(S.lineup).flat().reduce((sum,id)=>sum+(S.view.matchup?.pool?.find(p=>p.id===id)?.salary||0),0)}
function isCommish(){return !!S.me?.team?.isCommish}
function wDisabled(m){return !m||!m.pool?.length||["locked","final"].includes(S.view.week.status)}
function slot(key,title,max,pool){return '<div class="slot"><h3>'+title+' <span class="muted">('+S.lineup[key].length+'/'+max+')</span></h3>'+(S.lineup[key].map(id=>{const p=pool.find(x=>x.id===id);return p?'<div class="player selected"><span><b>'+esc(p.name)+'</b><small>'+esc(p.pos)+' · '+money(p.salary)+'</small></span><button class="remove" data-id="'+esc(id)+'" data-slot="'+key+'">Remove</button></div>':""}).join("")||'<p class="muted">Empty</p>')+'</div>'}
function player(p){const current=Object.entries(S.lineup).find(([k,ids])=>ids.includes(p.id));return '<div class="player '+(current?"selected":"")+'"><span><b>'+esc(p.name)+'</b><small>'+esc(p.pos)+' · '+esc(p.team)+' · '+p.proj+' proj · '+money(p.salary)+' · '+injuryLabel(p)+'</small></span>'+(current?'<button class="remove" data-id="'+esc(p.id)+'" data-slot="'+current[0]+'">Remove</button>':'<select class="assign" data-id="'+esc(p.id)+'"><option value="">Add to…</option>'+(p.pos==="QB"?'<option value="QB">QB</option>':"")+(p.pos==="RB"?'<option value="RB">RB</option>':"")+(p.pos==="WR"?'<option value="WR">WR</option>':"")+(["RB","WR","TE"].includes(p.pos)?'<option value="FLEX">FLEX</option>':"")+'</select>')+'</div>'}
function lineup(m,l){const pool=m.pool||[],groups={QB:pool.filter(p=>p.pos==="QB"),RB:pool.filter(p=>p.pos==="RB"),WR:pool.filter(p=>p.pos==="WR"),TE:pool.filter(p=>p.pos==="TE")},slots=[["QB","QB",1],["RB","RB",2],["WR","WR",3],["FLEX","FLEX",2]],sal=salary(l),complete=countLineup(S.lineup)===8,submitted=complete,status=S.view.week.status,live=liveForTeam(S.me?.team?.id),oppLive=liveForTeam(m.opponent?.id);let out='<section class="card"><div class="bar"><div><h2>My Team</h2><p class="muted">Your group: '+esc(S.me.groupName||"—")+' · Pool is shared only within your group.</p></div><div class="salary '+(sal>l.budget?"over":"")+'>'+money(sal)+' / '+money(l.budget)+'</div></div>';if(sal>l.budget)out+='<div class="cap-warning"><div class="capd">CAP’D</div><div><b>You’re over the salary cap.</b><span>Drop '+money(sal-l.budget)+' to submit your lineup.</span></div></div>';else out+='<p class="good">'+(complete?"8 / 8 players selected":"Select "+(8-countLineup(S.lineup))+" more players")+'</p>';out+=statusCard(m);out+='<div class="group-card"><div class="bar"><div><b>Your lineup status:</b> '+(submitted?'SUBMITTED':'NOT SUBMITTED')+'</div><span class="pill">'+esc(status.toUpperCase())+'</span></div>'+(live?.score!=null?'<p class="muted">Live score: <b>'+live.score+'</b> · '+(oppLive?.score!=null?'Opponent: <b>'+oppLive.score+'</b>':'')+'</p>':"")+'</div><div class="slots">'+slots.map(([key,title,max])=>slot(key,title,max,pool)).join("")+'</div><div class="card" style="margin-top:14px;background:#f8fafc"><h3>Available Players</h3><p class="muted">Add players below. FLEX accepts RB, WR or TE. Questionable players are allowed and marked Q.</p>'+groups.QB.map(player).join("")+groups.RB.map(player).join("")+groups.WR.map(player).join("")+groups.TE.map(player).join("")+'</div><div class="bar"><button id="saveLineup" type="button" '+(!complete||sal>l.budget||wDisabled(m)?"disabled":"")+'>'+(submitted?'Update Lineup':'Submit Lineup')+'</button>'+(isCommish()?'<span><button id="openWeek" class="secondary">Open Week</button> <button id="lockWeek" class="secondary">Lock Week</button> <button id="scoreWeek" class="secondary">Score Week</button></span>':"")+'</div>';if(m.result)out+=resultBox(m);out+='<p class="muted">Opponent: '+esc(m.opponent?.name||"Bye")+' · Your opponent receives the exact same player pool and salaries.</p></section>';return out}
function resultBox(m){const oid=m.opponent?.id,mine=S.me?.team?.id;return '<div class="card"><h3>Final score</h3><p>Your score: <b>'+(m.result.points[mine]??"—")+'</b></p><p>Opponent: <b>'+(oid?m.result.points[oid]:"—")+'</b></p></div>'}
function bindNav(){document.querySelectorAll("[data-nav]").forEach(b=>b.onclick=()=>{S.viewName=b.dataset.nav;render()})}
function bindWeekButtons(){document.getElementById("leave")?.addEventListener("click",()=>{localStorage.removeItem("sd_id");localStorage.removeItem("sd_code");location.reload()});document.getElementById("prev")?.addEventListener("click",()=>{if(S.week>1){S.week--;save();load()}});document.getElementById("next")?.addEventListener("click",()=>{if(S.week<S.league.numWeeks){S.week++;save();load()}});document.getElementById("enableAlerts")?.addEventListener("click",requestBrowserAlerts)}
function render(){if(!S.league||!S.view)return;let content=S.viewName==="team"?teamView():S.viewName==="matchups"?matchupsView():S.viewName==="standings"?standingsView():S.viewName==="players"?playersView():S.viewName==="rules"?rulesView():S.viewName==="commissioner"?commissionerView():dashboardView();shell(content)}
document.addEventListener("change",e=>{if(!e.target.classList.contains("assign"))return;const id=e.target.dataset.id,slot=e.target.value,max={QB:1,RB:2,WR:3,FLEX:2}[slot];if(!slot)return;if(S.lineup[slot].length>=max){alert(slot+" is full");e.target.value="";return}if(Object.values(S.lineup).flat().includes(id)){e.target.value="";return}S.lineup[slot].push(id);render()});
document.addEventListener("click",async e=>{if(e.target.classList.contains("remove")){const id=e.target.dataset.id,slot=e.target.dataset.slot;S.lineup[slot]=S.lineup[slot].filter(x=>x!==id);render();return}try{if(e.target.id==="saveLineup"){const btn=e.target;btn.disabled=true;btn.textContent="Submitting…";await api("/api/leagues/"+S.id+"/weeks/"+S.week+"/lineup",{method:"PUT",body:{lineup:S.lineup}});await load()}else if(["openWeek","dashOpen"].includes(e.target.id)){await api("/api/leagues/"+S.id+"/weeks/"+S.week+"/open",{method:"POST"});await load()}else if(e.target.id==="generatePool"){const btn=e.target;btn.disabled=true;btn.textContent="Generating…";try{await api("/api/leagues/"+S.id+"/weeks/"+S.week+"/generate-pool",{method:"POST"});await load();alert("Player pool generated successfully. Your group player pool is now READY.");}catch(x){btn.disabled=false;btn.textContent="Generate Player Pool";alert("Player pool generation failed: "+x.message)}}else if(["lockWeek","dashLock"].includes(e.target.id)){await api("/api/leagues/"+S.id+"/weeks/"+S.week+"/lock",{method:"POST"});await load()}else if(["scoreWeek","dashScore"].includes(e.target.id)){await api("/api/leagues/"+S.id+"/weeks/"+S.week+"/score",{method:"POST"});await load()}}catch(x){alert(x.message)}});
if(S.id&&S.code)load();else home();